---
apiVersion: v1
kind: Pod
metadata:
  name: zabbix-server-mysql
  labels:
    name: zabbix-server-mysql
    app: zabbix-app
spec:
  containers:
    - name: zabbix-server-mysql
      image: zabbix/zabbix-server-mysql:latest
      env:
        - name: DB_SERVER_HOST
          value: "192.168.43.128"	
        - name: MYSQL_DATABASE
          value: "zabbix"	
        - name: MYSQL_USER
          value: "root"	
        - name: MYSQL_PASSWORD
          value: "root123"	
        - name: MYSQL_ROOT_PASSWORD
          value: "root123"	
        - name: ZBX_JAVAGATEWAY
          value: "zabbix-java-gateway"	  
      ports:           
        - containerPort: 10051
          name: zabbix-sql
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server-mysql
  labels:
    name: zabbix-server-mysql
    app: zabbix-app
spec:
  ports:
    - port: 10051
      targetPort: 10051
  selector:
    name: zabbix-server-mysql
    app: zabbix-app
  type: NodePort
---
